### ISSUE TITLE
Als productowner wil dit dat formulier 'Aanmeldformulier 1.Hoorn' als klantreis beschikbaar is op zuid-drecht

### ISSUE THREAD

**Issue by matthiasoliveiro** [Team-online-stage/Online-stage-platform#126]
"Maak eerst een verzoekType en vervolgens een procesType aan dit formulier, denk er aan beide componenten (VTC en PTC) lokaal op te spinnen en te testen voordat je jouw code commit en pushed. Het formulier moet in de stijl van Zuid-Drecht zijn dev.zuid-drecht.nl. 

Voorbeeld formulier: https://formulieren.hoorn.nl/formulier/nl-NL/punthoorn/sc1punthoornAanmeldformulier.aspx"

**Comment by MarkBout** [comment]
hey @matthiasoliveiro Sarai en ik kwamen erachter dan dit formulier en die van issue #65 we hebben deze nu allebij gemaakt, hoe kunnen we dit oplossen want we hebben nu 2 dezelfde formulieren op 2 verschillende issues

**Comment by matthiasoliveiro** [comment]
Ah kijk aan deze is dubbel, dat is jammer.
We zouden we als volgt kunnen oppakken, combineer de formulieren tot 1 formulier waar je uit elk formulier de beste dingen mee pakt. Uiteindelijk hebben we hier maar 1 formulier van nodig. Een van de issues kan dus ook gesloten worden, met de mededeling dubbel.

**Comment by MarkBout** [comment]
Dubbel
