### ISSUE TITLE
Als productowner wil dit dat formulier 'Aanvraag JA/NEE of NEE/NEE sticker' als klantreis beschikbaar is op zuid-drecht

### ISSUE THREAD

**Issue by matthiasoliveiro** [Team-online-stage/Online-stage-platform#72]
"Maak eerst een verzoekType en vervolgens een procesType aan dit formulier, denk er aan beide componenten (VTC en PTC) lokaal op te spinnen en te testen voordat je jouw code commit en pushed. Het formulier moet in de stijl van Zuid-Drecht zijn dev.zuid-drecht.nl. 

Voorbeeld formulier: https://formulieren.hoorn.nl/formulier/nl-NL/DefaultEnvironment/scJaNeeSticker.aspx"

**Comment by ginokok1996** [comment]
Ik zie als omschrijving dat ik een parkeervergunning kan aanvragen met het process?

**Comment by ginokok1996** [comment]
Ik zag dat je in je vtc voornaam en achternaam weggehaald hebt maar in je ptc word het property nog wel aangeroepen op line 79.
Die moet er dus ook nog even uit.
Nu krijg ik namelijk een error als ik door het process wil lopen.
En de description van het ptc staat nog op:
Hier kunt u een parkeervergunning aanvragen.
op line 40.
