### ISSUE TITLE
Als productowner wil dit dat formulier 'Contactformulier bijzondere bijstand' als klantreis beschikbaar is op zuid-drecht

### ISSUE THREAD

**Issue by matthiasoliveiro** [Team-online-stage/Online-stage-platform#81]
"Maak eerst een verzoekType en vervolgens een procesType aan dit formulier, denk er aan beide componenten (VTC en PTC) lokaal op te spinnen en te testen voordat je jouw code commit en pushed. Het formulier moet in de stijl van Zuid-Drecht zijn dev.zuid-drecht.nl. 

Voorbeeld formulier: https://formulieren.hoorn.nl/formulier/nl-NL/DefaultEnvironment/scBijzondereBijstandContact.aspx"

**Comment by ginokok1996** [comment]
De git build is gefaald.
Op line 93 van je fixtures zet je een comment.
Maar je mist een /.
Probeer als je klaar bent met een process lokaal op te spinnen dan krijg je deze errors ook te zien.

**Comment by ginokok1996** [comment]
@ginokok1996

**Comment by ginokok1996** [comment]
Bij dit formulier heb ik niet het gevoel dat het adres wat ik opgeef anders zou kunnen zijn dan mijn eigen adres.
En al je adres gegevens staan ook in je digid.
Dus adres gegevens zou ik bij deze weglaten en dus alleen vragen om:
-telefoon
-email adres.

Geboorte datum is in dit geval ook niet nodig aangezien dat ook vermeld staat in je digid inlog gegevens.
